<a href="https://colab.research.google.com/github/MayerAnnamaria/Statistics_examples/blob/master/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
#the machine learning model will expect these two things separatly, the dependent variable and the features (independent) variables
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values # all the columns from the dataset, except the last column. : means all the rows,
y = dataset.iloc[:, -1].values # the last column, -1 is the index of the last column

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer

#replace the missing value by the average of all the values in the column (replacing it by the average of all the salaries - salary column, also replaces missing age with age mean)
# this is a class: SimpleImputer
#missing_values=np.nan - specify which values do we want to replace. What do we want to replace it by: strategy='mean'
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') # this is just an object
# we specify X because we want to replace the things in the column. 
#We select all the rows (:), 
#Select first and second column: 1:3 is the age and the salary column
#the best is if here we select all the numberical columns, to be sure that we replace all the missing data
imputer.fit(X[:, 1:3]) # the fit method will do the action, will compute the average of the salaries

#here it has to be the same as before, because this replaces
X[:, 1:3] = imputer.transform(X[:, 1:3]) # transform will replace the missing values by the average salaries


In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# the 0 is the first column that we want to transform/recode
# remainder='passthrough' - because of this the numerical variables will not be recoded (those we do not have to recode)
# I use OneHotEncoder for ordinal, nominal variables with more than 2 attributes (when you have several categories)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
#I use LabelEncoder for variables to recode the y column into 'yes and No's into dummy variable
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
#this will create 4 different variables
# X: independent variables
# y: dependent variable

# test_size = 0.2 -------------
# test_size: 80% observation will go into the training set, 20 % observation is going to the test set
# so in our example, N=10, so: 8 customers will go into the training set and 2 will go into the test set (these will be taken randomly)
# random_state = 1 : it makes sure that the function will have the same random factors
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
# we have to employ this after splitting the dataset into training and test set in order to avoid information linkage because the test set has to be something new
# we put all our features on the same scales
# we do not have to apply this for all the machine learning models.

#There are 2 techniques: 1. standardization, 2. normalization
# use normalization, when most of your features (indep variables) are normally distributed
# we can use standardization all the time

# here we standardize the independent variables, both for the training set and test set, but only for the numerical variables
# we only have to apply them for numerical variables (interval, scale)
sc = StandardScaler()
# here we apply standardization for X_train and X_test:
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:]) #age and salary columns
# here we have to apply the same scaler that was used on the training set
X_test[:, 3:] = sc.transform(X_test[:, 3:]) #age and salary columns

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
